### ISSUE TITLE
Fail on Inference

### ISSUE THREAD

**Issue by SihengLi99** [AILab-CVC/SEED#10]
Hi, nice work!

However, I follow the instruction in readme, while I got some problems:

![image](https://github.com/AILab-CVC/SEED/assets/75015153/a0d022fd-7195-413e-8bc9-b5e1069fec9a)

It seems that the vocabulary file is missing
<img width="1289" alt="image" src="https://github.com/AILab-CVC/SEED/assets/75015153/5de38ada-4017-4f2e-95c3-52701fe74b28">

**Comment by SihengLi99** [comment]
I have found that the problem derived from a wrong error message from the huggingface.
The inference pipeline is excellent!

Thanks!

**Comment by czhhzc** [comment]
How do you solve the problem? I met the same question.

**Comment by sysu-yyxc** [comment]
> I have found that the problem derived from a wrong error message from the huggingface. The inference pipeline is excellent!
> 
> Thanks!

I encountered the same problem, how can I sovle this problem?
