### ISSUE TITLE
install.sh not working 

### ISSUE THREAD

**Issue by shubhamgarg21** [AILab-CVC/SEED#29]
In the Training SEED Tokenization step 1, the command `sh install.sh` is failing. 
Inside this script there are following commands : 
```
cd stable_diffusion
pip install -r requirements.txt
pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip
cd ..
pip install -e stable_diffusion
```

but there is no stable_diffusion folder inside SEED_Tokenizer folder. am i missing something?

**Comment by geyuying** [comment]
Sorry for the mistake. You do not need to install stable_diffusion and we have updated install.sh.
