### ISSUE TITLE
question about image2text training？

### ISSUE THREAD

**Issue by zzchust** [AILab-CVC/SEED#3]
<img width="880" alt="image" src="https://github.com/AILab-CVC/SEED/assets/6135871/a81ccbd4-7a07-43d2-887c-8235e7a07503"> 1. 图像->文本： 这里输入的是图像的token-ID还是vector啊， 我看这里说对图像的表示用FC进行了处理映射，然后再和text embeeding串起来的？

**Comment by geyuying** [comment]
输入的是图像的tokein-ID在visual codebook里对应的visual codes(vector)，再接FC（使得和word embedding的dimenison对齐）。
