### ISSUE TITLE
hydra.errors.InstantiationException: Error locating target './models.seed_llama_tokenizer.SeedLlamaTokenizer.from_pretrained', set env var HYDRA_FULL_ERROR=1 to see chained exception

### ISSUE THREAD

**Issue by cxjtju** [AILab-CVC/SEED#49]
when i execute CUDA_VISIBLE_DEVICES=0 python3 scripts/seed_tokenizer_inference.py, encounter 
**hydra.errors.InstantiationException: Error locating target './models.seed_llama_tokenizer.SeedLlamaTokenizer.from_pretrained', set env var HYDRA_FULL_ERROR=1 to see chained exception.**
![image](https://github.com/user-attachments/assets/7e69256c-5df1-4a88-902c-7cb29c28d069)

**Comment by cxjtju** [comment]
![image](https://github.com/user-attachments/assets/3aad319d-5d12-4dc2-aa73-62be5c8149e5)

**Comment by DQYZHWK** [comment]
how to fix this issue
