### ISSUE TITLE
About Gradio Version

### ISSUE THREAD

**Issue by MajorDavidZhang** [AILab-CVC/SEED#8]
Hello,

Firstly, I'd like to express my gratitude for your efforts in developing this project. While attempting to run `start_frontend_14b.sh`, I've run into some compatibility issues with Gradio. It appears that the script relies on an older version of Gradio that isn't compatible with the latest release (4.3.0).

To resolve this, I downgraded Gradio to version 3.50.0, after which everything worked as expected. I suggest specifying the particular version of Gradio in the `requirements.txt` file to prevent similar issues for other users.

**Comment by geyuying** [comment]
Thank you so much for the suggestions!
