### ISSUE TITLE
CIDEr reproduce hyperparameter

### ISSUE THREAD

**Issue by zheedong** [AILab-CVC/SEED#9]
Hello, thank you for your research and I'm very interested in it. I'd like to reproduce your research results, so could you tell me about the specific evaluation setting?

**Comment by geyuying** [comment]
Thank you for your interest in our work. For evaluating image captioning, we use model.generate(num_beams=5, do_sample=False).

**Comment by zheedong** [comment]
Hi, thanks for your reply. Thanks to your reply, it was successful to reproduce your CIDEr results.
I have some other questions about your works.

1. Which hyperparameter do you use for CLIP Score image generation?
2. Do you have any measurement about COCO test set FID?

Thank you.
